// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd6Se-jWPiWHc4GkuQmD_DPT0i_EJD-eY',
    appId: '1:191043264136:web:10bffe01349477e475893d',
    messagingSenderId: '191043264136',
    projectId: 'familyfood-fa2e6',
    authDomain: 'familyfood-fa2e6.firebaseapp.com',
    storageBucket: 'familyfood-fa2e6.firebasestorage.app',
    measurementId: 'G-179DEX3S4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYTiiJc1S9Cd07MbdTyh9kOEl9WRbuk3c',
    appId: '1:191043264136:android:2a25451d5d6675a375893d',
    messagingSenderId: '191043264136',
    projectId: 'familyfood-fa2e6',
    storageBucket: 'familyfood-fa2e6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP008IC6Goyph-O5_g-9u8s8IDax8H3kk',
    appId: '1:191043264136:ios:ecf613806e4197dd75893d',
    messagingSenderId: '191043264136',
    projectId: 'familyfood-fa2e6',
    storageBucket: 'familyfood-fa2e6.firebasestorage.app',
    iosBundleId: 'com.example.familyFoodTracker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP008IC6Goyph-O5_g-9u8s8IDax8H3kk',
    appId: '1:191043264136:ios:ecf613806e4197dd75893d',
    messagingSenderId: '191043264136',
    projectId: 'familyfood-fa2e6',
    storageBucket: 'familyfood-fa2e6.firebasestorage.app',
    iosBundleId: 'com.example.familyFoodTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd6Se-jWPiWHc4GkuQmD_DPT0i_EJD-eY',
    appId: '1:191043264136:web:92e12ebdac7aa44875893d',
    messagingSenderId: '191043264136',
    projectId: 'familyfood-fa2e6',
    authDomain: 'familyfood-fa2e6.firebaseapp.com',
    storageBucket: 'familyfood-fa2e6.firebasestorage.app',
    measurementId: 'G-Y4LETDTXX8',
  );
}
